sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sasioin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sasioin/docker-react npm run test --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-172446579289"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
